service:
  type: ClusterIP
  port: 9000

persistence:
  enabled: true
  storageClass: local-path
  size: 1Gi

nodeSelector:
  kubernetes.io/hostname: k3s-server-01

ca:
  name: Homelab CA
  address: ":9000"
  dns: "step-ca.step-ca.svc.cluster.local,step-ca"
  provisioner:
    name: acme
    type: ACME
