ca:
  name: Homelab CA
  address: ":9000"
  dns: "step-ca-step-certificates,step-ca-step-certificates.step-ca,step-ca-step-certificates.step-ca.svc.cluster.local"
  provisioner:
    name: acme
    type: ACME

service:
  type: ClusterIP
  port: 9000

persistence:
  enabled: true
  storageClass: local-path
  size: 1Gi

nodeSelector:
  kubernetes.io/hostname: k3s-server-01
