inject:
  enabled: true
  config:
    files:
      ca.json:
        root: /home/step/certs/root_ca.crt
        federateRoots: []
        crt: /home/step/certs/intermediate_ca.crt
        key: /home/step/secrets/intermediate_ca_key
        address: :9000
        dnsNames:
          - step-ca.step-ca.svc.cluster.local
          - step-ca
        logger:
          format: json
        db:
          type: badgerV2
          dataSource: /home/step/db
        authority:
          provisioners:
            - type: ACME
              name: acme
        tls:
          minVersion: 1.2

  certificates:
    intermediate_ca: ""
    root_ca: ""

  secrets:
    ca_password: ""
    provisioner_password: ""

service:
  type: ClusterIP
  port: 9000

persistence:
  enabled: true
  storageClass: local-path
  size: 1Gi

nodeSelector:
  kubernetes.io/hostname: k3s-server-01
