apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-platform
  namespace: hello-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-platform
  template:
    metadata:
      labels:
        app: hello-platform
    spec:
      containers:
        - name: hello-platform
          image: ghcr.io/mihai7785/hello-platform:e34776b
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-platform
  namespace: hello-platform
spec:
  selector:
    app: hello-platform
  ports:
    - port: 80
      targetPort: 8080
