all:
  children:
    k3s_cluster:
      children:
        k3s_server:
          hosts:
            k3s-server-01:
              ansible_host: 192.168.1.201
        k3s_workers:
          hosts:
            k3s-worker-01:
              ansible_host: 192.168.1.202
            k3s-worker-02:
              ansible_host: 192.168.1.204
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/homelab_key
        ansible_python_interpreter: /usr/bin/python3