grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca-issuer
    hosts:
      - grafana.homelab.local
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.homelab.local
  adminPassword: "admin"
  persistence:
    enabled: true
    storageClassName: nfs-ssd
    size: 5Gi
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100

prometheus:
  prometheusSpec:
    retention: 15d
    initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:2000 /prometheus && chmod 775 /prometheus"]
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: prometheus-db
            mountPath: /prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-ssd
          resources:
            requests:
              storage: 20Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca-issuer
    hosts:
      - prometheus.homelab.local
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.homelab.local

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca-issuer
    hosts:
      - alertmanager.homelab.local
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.homelab.local

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false
