apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-issuer
spec:
  acme:
    server: https://step-ca-step-certificates.step-ca.svc.cluster.local:9000/acme/acme/directory
    skipTLSVerify: true
    privateKeySecretRef:
      name: step-ca-acme-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
